### ISSUE TITLE
Lidar com restrição de Atributos de Raça

### ISSUE THREAD

**Issue by isaacbatst** [YuriAlessandro/gerador-ficha-tormenta20#127]
Ex: Lefou coloca +2 em atributos aleatórios, menos carisma

**Comment by GustavoAC** [comment]
![image](https://user-images.githubusercontent.com/14988101/111087467-96b6f900-8500-11eb-81cd-b709bb17cf8d.png)
Não é um problema porque o -2 em carisma também conta como um modificador, aí carisma fica marcado como um atributo modificado e já não pode colocar mais nenhum bônus nele.

![image](https://user-images.githubusercontent.com/14988101/111087514-cb2ab500-8500-11eb-826f-054174041cbd.png)
Um humano bardo sempre vai começar colocando +2 em Carisma, mas um Lefou começa com -2 e não tenta mais colocar. Sempre esteve resolvido olha só
