### ISSUE TITLE
Refletir efeitos de Habilidades selecionadas na ficha do personagem

### ISSUE THREAD

**Issue by GustavoAC** [YuriAlessandro/gerador-ficha-tormenta20#133]
Gerar efeitos a partir de lambdas que afetam diretamente a ficha do personagem.
Pensar em ordem de execução que nem feito com perícias

**Comment by isaacbatst** [comment]
O start tá em prod: Humano.

To fazendo raça a raça já fazendo os testes pra ela.

**Comment by isaacbatst** [comment]
- [x] Humano 
- [x] Anão 
- [ ] Dahlan
- [ ] Elfo
- [ ] Goblin
- [ ] Lefou
- [ ] Minotauro
- [ ] Qareen
- [ ] Golem
- [ ] Hynne
- [ ] Kliren
- [ ] Medusa
- [ ] Osteon
- [ ] Seriea
- [ ] Sílfide
- [ ] Suraggel
- [ ] Trog

De preferência com testes inclusos

**Comment by isaacbatst** [comment]
Fazendo @Dahllan

**Comment by isaacbatst** [comment]
@YuriAlessandro  fazendo as actions das sereias
