### ISSUE TITLE
Implementar ordem final de geração de ficha

### ISSUE THREAD

**Issue by GustavoAC** [YuriAlessandro/gerador-ficha-tormenta20#156]
Atributos (somente rolagens)
Sexo
Raça
Sexo, Raça -> Nome

Classe
Classe -> Origem (se alguma)

Itens iniciais // vazios
Magias iniciais // vazias

Classe -> PV inicial
Classe -> PM inicial
Classe, Raça -> Atributos finais (somando os da raça pela preferência da classe)
Defesa inicial = 10
Classe, Raça, Origem -> Pericias na ordem já definida
Classe, Raça, Origem, Items iniciais, Magias iniciais -> Poderes na ordem: (Poderes podem afetar e modificar tudo gerado até agora)
     Raça
     Classe
     Origem

Origem, Classe -> Itens gerados
Defesa atual, equipamentos, atributos -> Recalcular defesa
Classe, Raça -> Religião
Magias iniciais -> Magias
Raça -> Tamanho
Raça, Equipamentos -> Deslocamento

tudo acima é character sheet

(enquanto nível atual < nivel desejado) {
    Aumentar PV e PM
    Seguir spell path
    Pra cada poder em poderes:
        sheet, poder -> sheet // atualiza a ficha pra o nível atual pelos poderes que modificam ao upar
    
    nivel, classe, poderesgerais -> escolher poder novo aleatorio
    sheet, poder novo -> sheet
}

retorne sheet

**Comment by isaacbatst** [comment]
Poderes e perícias não vão ter que ser gerados juntos? Por causa das origens sortearem  aleatoriamente dentre um grupo de perícias ou origens.
