### ISSUE TITLE
Erro do oficio

### ISSUE THREAD

**Issue by YuriAlessandro** [YuriAlessandro/gerador-ficha-tormenta20#157]
Se você escolher Inventor com Assistente de Laboratório ele tenta escolher OFICIO duas vezes e dá erro. Verificar depois como resolver

**Comment by isaacbatst** [comment]
Corrigindo, só tava errado na lista de perícias da origem. Mas vou dar uma revisada no código tb

**Comment by isaacbatst** [comment]
Subi a correção no #160 mas vou deixar aberto pra quando pegar já fazer esses testes de pericias

**Comment by isaacbatst** [comment]
Testes feitos, verificando cada função envolvida verificando se não retorna nada repetido
