### ISSUE TITLE
Conflito nas divindades do druida

### ISSUE THREAD

**Issue by RuanOniiKun** [YuriAlessandro/gerador-ficha-tormenta20#212]
Druida pode ser devoto de Allihanna, Megalokk ou Oceano, no gerador ele está vindo com Allihanna, Aharadak ou Oceano, o deus dos montros e da tormenta ficou trocado.

**Comment by YuriAlessandro** [comment]
Boa, acho que cometemos um engano mesmo. Obrigado por avisar. Vou deixar registrado aqui em baixo a regra:

![image](https://user-images.githubusercontent.com/14967048/111505307-4372bf80-8727-11eb-972f-4eeb1287f942.png)

Deve sair como patch de correções da 1.0
