### ISSUE TITLE
Ficha de Minotauro com Habilidades de Golem

### ISSUE THREAD

**Issue by dcatein** [YuriAlessandro/gerador-ficha-tormenta20#214]
Uma das fichas geradas de um Minotauro veio com as habilidades de Golem no Passo-a-passo.

![Screenshot_20210317-171813](https://user-images.githubusercontent.com/18426972/111533272-5ac0a580-8745-11eb-9e2b-c1eed783269c.png)
![Screenshot_20210317-171805](https://user-images.githubusercontent.com/18426972/111533275-5bf1d280-8745-11eb-9e4b-af757630982a.png)

**Comment by YuriAlessandro** [comment]
@dcatein qual foi a habilidade em questão?

**Comment by isaacbatst** [comment]
@YuriAlessandro  chassi no passo 17

**Comment by isaacbatst** [comment]
@YuriAlessandro  o problema é no registro dos steps 
```js
substeps.push({
          name: 'Chassi',
          value: `+1 defesa (${sheet.defesa} + 1 = ${finalDefense})`,
        });
``` 

tá assim lá

**Comment by dcatein** [comment]
Não sei se deveria abrir outra Issue, mas as habilidades de Trog tbm não estão aparecendo

**Comment by YuriAlessandro** [comment]
Boa, já abri issue para essa segunda também. Vamos corrigindo por aqui.

@isaacbatst hehe, acontece
