### ISSUE TITLE
Exportar em formato .json para importar via Foundry Vtt

### ISSUE THREAD

**Issue by alvesramonz** [YuriAlessandro/gerador-ficha-tormenta20#265]
[fvtt-Actor-Testinho.txt.zip](https://github.com/YuriAlessandro/gerador-ficha-tormenta20/files/6207582/fvtt-Actor-Testinho.txt.zip)

**Comment by alvesramonz** [comment]
Foundry usa o formato acima de .json

**Comment by isaacbatst** [comment]
[Exemplo de personagem com magias e poderes](https://gist.github.com/isaacbatst/fbabb68cc14dbda58ae628cd4019d8d2)

**Comment by isaacbatst** [comment]
Conversões:
- [ ] Informações Básicas
- [ ] Poderes
- [ ] Efeitos dos poderes
- [ ] Magias
- [ ] Inventário
- [ ] Armas
- [ ] Perícias

**Comment by isaacbatst** [comment]
Tudo que se arrasta Compêndio tem que ter uma relação com os itens que estam cadastrados lá, pelo ID provavelmente.
