### ISSUE TITLE
pfv arruma isso

### ISSUE THREAD

**Issue by betagame13** [YuriAlessandro/gerador-ficha-tormenta20#343]
Salve na paz?

Estou achando muito útil a ferramenta mas infelizmente o link para geração de ameaças/monstros está quebrando 
![Erro 503](https://user-images.githubusercontent.com/30901466/215266372-313f9468-9fab-479d-bcf7-a381541fc384.png).

Na minha visão essa seria uma ótima implementação.

_Originally posted by @LeandroMohr in https://github.com/YuriAlessandro/gerador-ficha-tormenta20/discussions/342_

**Comment by YuriAlessandro** [comment]
Esse projeto era de terceiros, não foi feito por mim e saiu do ar. Removi o link para ele do projeto.
