### ISSUE TITLE
Matriz de divindades

### ISSUE THREAD

**Issue by YuriAlessandro** [YuriAlessandro/gerador-ficha-tormenta20#63]
@GustavoAC vai criar uma matriz de divindades para definir qual raça/classe deve receber qual divindade de forma mais precisa.

**Comment by isaacbatst** [comment]
@GustavoAC ao invés de colocar vários 0 como a gente conversou, dá pra mandar também um `{}` que as entradas vão ser só os deuses diferentes de 0. E então, interpretar o resto como 0 por padrão.
