### ISSUE TITLE
Adicionar mais testes

### ISSUE THREAD

**Issue by YuriAlessandro** [YuriAlessandro/gerador-ficha-tormenta20#70]
Adicionar mais testes para gerador de nomes, para alterações de raças e alterações de classe

**Comment by isaacbatst** [comment]
Puxar isso aqui antes da Origem pra não acumular muita coisa sem teste.

**Comment by isaacbatst** [comment]
- [ ] Equipamentos
- [ ] Origem
- [ ] Magia
- [ ] Pericia
- [ ] Nomes
- [ ] Poderes

**Comment by isaacbatst** [comment]
Testes de pericias tem que ser refeitos para a nova implementação
